### ISSUE TITLE
Essential dependencies need by npm i

### ISSUE THREAD

**Issue by thekingofcity** [shadowsocks/shadowsocks-restful-api#6]
# For clean ubuntu 16.04.4 LTS install, these dependencies are required.

**`apt-get install python-dev`**
[Python: ImportError: No module named compiler.ast](https://github.com/lovell/sharp/issues/1087)
for
```
> unix-dgram@2.0.2 install /root/shadowsocks-restful-api/node_modules/unix-dgram
> node-gyp rebuild

Traceback (most recent call last):
  File "/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py", line 13, in <module>
    import gyp
  File "/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 8, in <module>
    import gyp.input
  File "/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 5, in <module>
    from compiler.ast import Const
ImportError: No module named compiler.ast
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:336:16)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.4.0-109-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /root/shadowsocks-restful-api/node_modules/unix-dgram
gyp ERR! node -v v8.11.4
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! unix-dgram@2.0.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the unix-dgram@2.0.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**`apt-get install make g++`**
for
```
> unix-dgram@2.0.2 install /root/shadowsocks-restful-api/node_modules/unix-dgram
> node-gyp rebuild

make: Entering directory '/root/shadowsocks-restful-api/node_modules/unix-dgram/build'
  CXX(target) Release/obj.target/unix_dgram/src/unix_dgram.o
make: g++: Command not found
unix_dgram.target.mk:93: recipe for target 'Release/obj.target/unix_dgram/src/unix_dgram.o' failed
make: *** [Release/obj.target/unix_dgram/src/unix_dgram.o] Error 127
make: Leaving directory '/root/shadowsocks-restful-api/node_modules/unix-dgram/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.4.0-109-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /root/shadowsocks-restful-api/node_modules/unix-dgram
gyp ERR! node -v v8.11.4
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! unix-dgram@2.0.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the unix-dgram@2.0.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by Eggham** [comment]
Hi,

Thanks for reporting bug/error. How did you get the error? Could you reproduce the error? Could you describe the steps you did before the error?

**Comment by Eggham** [comment]
got it! thx. README has been updated.
